### ISSUE TITLE
common issue / question

### ISSUE THREAD

**Issue by dphn** [hrevert/HtSession#1]
Hi! 
I would like to clarify a few issues /questions :)

I do not know whether this is a bug.

https://github.com/hrevert/HtSession/blob/master/src/HtSession/Factory/ModuleOptionsFactory.php#L20

in my htsession.global.php

```
return [
    'htsession' => [
        'options' => [ // <<< !!!!!!!!
            'enable_session_set_save_handler' => false,
            'config_class' => 'Zend\Session\Config\SessionConfig',
            'config_options' => [
                'save_path' => './data/session',
            ],
        ],
    ],
];
```

Do I need here nesting level "options"? The level "htsession" is already options?

**_And thank you, it's interesting module.**_

**Comment by ojhaujjwal** [comment]
That is not a bug.
Previously, it was like [this](https://github.com/hrevert/HtSession/blob/efbd90b263de8f1b05a348faa515c096a7e29495/config/HtSession.global.php#L129).
Marco Pivotta advised me to remove that part.

**Comment by ojhaujjwal** [comment]
And, yes that`s needed.

**Comment by dphn** [comment]
Ok, thanks.

**Comment by ojhaujjwal** [comment]
@dphn Hey. I have added a new feature. See [here](https://github.com/hrevert/HtSession/blob/master/docs/Session%20Validators.md). New validators exist outside `option`!

**Comment by dphn** [comment]
Excuse me, in connection with the events in my country (Ukraine) I have temporarily suspended work in this direction. Hopefully this will not last long.
