### ISSUE TITLE
Log out when multiple zfcUser

### ISSUE THREAD

**Issue by stijnhau** [hrevert/HtSession#3]
I have multiple ZfcUser running on my machine(test enviroment and different projects).
Using it with https://github.com/hrevert/HtSession.
The login action works correctly.
The logout action logs me out on all the versions.

**Comment by ojhaujjwal** [comment]
You need to store session data of different applications in different place. For example, you can store them in different database or different path.

**Comment by stijnhau** [comment]
With 1 i store them in databse (default settup no changes in config file)
the other 1 isn't using this module.

**Comment by stijnhau** [comment]
Don't know witch of the modules creates this bug soi created issue in both of them.
https://github.com/ZF-Commons/ZfcUser/issues/478
for link to other issue.
